# Generated by Django 4.0.3 on 2022-03-23 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_multichoice_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='player_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, unique=True)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='user_player_choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_status', models.BooleanField(default=False)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_multichoice_app.user_info')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_multichoice_app.player_info')),
            ],
            options={
                'unique_together': {('email', 'name')},
            },
        ),
    ]
