# Generated by Django 4.0.3 on 2022-03-23 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_multichoice_app', '0002_player_info_user_player_choice'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user_player_choice',
            unique_together=set(),
        ),
    ]
