# Generated by Django 4.0.3 on 2022-03-23 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_multichoice_app', '0003_alter_user_player_choice_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_player_choice',
            name='choice_status',
        ),
        migrations.RemoveField(
            model_name='user_player_choice',
            name='name',
        ),
        migrations.AddField(
            model_name='user_player_choice',
            name='name',
            field=models.ManyToManyField(to='user_multichoice_app.player_info'),
        ),
    ]
