# Generated by Django 4.0.3 on 2022-03-23 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_multichoice_app', '0004_remove_user_player_choice_choice_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='email',
            field=models.EmailField(max_length=500, unique=True),
        ),
    ]
