# Generated by Django 4.0.3 on 2022-03-17 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_detail_app', '0002_user_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_details',
            old_name='status',
            new_name='subscribe_status',
        ),
    ]
