# Generated by Django 4.0.3 on 2022-03-21 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_detail_app', '0003_rename_status_user_details_subscribe_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='player_choices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_detail_app.user_details')),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_detail_app.players')),
            ],
        ),
    ]
