# Generated by Django 4.0.3 on 2022-03-21 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_detail_app', '0004_player_choices'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='player_choices',
            unique_together={('email', 'name')},
        ),
    ]
