# Generated by Django 4.0.3 on 2022-03-21 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_detail_app', '0005_alter_player_choices_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='player_choices',
            unique_together=set(),
        ),
    ]
