# Generated by Django 4.0.3 on 2022-03-21 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_detail_app', '0008_alter_player_choices_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='subscribe_status',
            field=models.BooleanField(default=False),
        ),
    ]
