# Generated by Django 4.0.3 on 2022-03-21 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_detail_app', '0009_alter_players_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player_choices',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
